In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# arange

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

# zeros and ones

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Linspace

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

# eye


In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# random

In [ ]:
np.random.rand(2)

array([0.74476081, 0.64604103])

In [ ]:
np.random.rand(5,5)

array([[0.39573148, 0.94688352, 0.3081953 , 0.43163756, 0.04381741],
       [0.96136091, 0.22261835, 0.54273483, 0.01955282, 0.80679107],
       [0.36961907, 0.76960596, 0.23942326, 0.97260823, 0.86951904],
       [0.33675017, 0.51543349, 0.88872479, 0.53581341, 0.91290089],
       [0.89896853, 0.48557144, 0.33216003, 0.12955716, 0.79417922]])

# randn

In [ ]:
np.random.randn(2)

array([-0.8271493 ,  0.45865114])

In [ ]:
np.random.randn(15,5)

array([[-0.34622295, -1.21110702,  1.68246028, -2.19223453,  0.69884811],
       [-2.68600145, -1.03055092, -0.05063441, -0.26775407, -0.82256442],
       [ 1.24678951, -0.75861361, -0.38511315,  0.2294485 , -0.30653533],
       [ 0.90808933,  0.20215159,  0.25571069,  0.46376467, -1.15029472],
       [-0.88472285,  0.13383141, -2.29181193, -0.04542133, -0.1552897 ],
       [-0.77374211, -0.4835888 , -0.86250438,  1.17425754,  0.4239772 ],
       [ 0.14954591, -0.79033342,  1.57953416,  1.38077102,  0.7592118 ],
       [-0.14121745,  1.07972576,  0.17225335, -0.7241311 , -0.50444118],
       [-0.53500784, -1.09786115,  0.67876148,  0.62482734,  0.2053729 ],
       [ 1.25457381,  1.3412573 ,  0.46215195, -0.02636964,  1.17652074],
       [ 1.09053786,  0.37660585, -0.35737347, -0.48324106, -2.06409798],
       [ 0.58112076, -0.34335055, -0.96766481,  0.27848934,  0.66292995],
       [-0.3493187 ,  2.17399941,  0.05542581, -1.00264577, -1.49541222],
       [ 1.13050801, -1.36061454,  0.0

# randint

In [ ]:
np.random.randint(1,100)

12

In [ ]:
np.random.randint(1,100,10)

array([43, 75, 36, 93, 67, 35,  3, 30, 60, 54])

# Array Attributes and Methods

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([22, 40,  6,  4, 14,  9, 24,  1, 34, 47])

# Reshape

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# max,min,argmax,argmin

In [ ]:
ranarr

array([22, 40,  6,  4, 14,  9, 24,  1, 34, 47])

In [ ]:
ranarr.max()

47

In [ ]:
ranarr.argmax()

9

In [ ]:
ranarr.min()

1

In [ ]:
ranarr.argmin()

7

# Shape

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

# dtype

In [ ]:
arr.dtype

dtype('int64')